### ISSUE TITLE
样式BUG

### ISSUE THREAD

**Issue by smartbeng** [saintwinkle/hexo-theme-scribble#1]
首页每个头部标签下面有一条虚线 希望赶快改进呀

**Comment by saintwinkle** [comment]
原版主题就是那样的：http://chloerei.com/scribble 。这个主题暂时不会对原版样式做出改动，请谅解。

如果确实有需求的话，可以自行到主题文件中删除这一行：
https://github.com/saintwinkle/hexo-theme-scribble/blob/master/source/css/style.css#L154

不知道有没有正确理解你的意思，以上。

**Comment by smartbeng** [comment]
我觉得在这里我们不需要纠结什么原版，开源的力量说白了就是无限制的修改BUG ，我相信你可以做的很好！

**Comment by smartbeng** [comment]
关键是头部上满的虚线一直在，鼠标光标没移动上去就有，头部下导航栏的则是好的。目前我删了这个样式了，但是我们想办法把他解决岂不是更好！

**Comment by saintwinkle** [comment]
原本的 css 特意把导航部分的链接样式单独拎了出来，我认为原作者可能是想强调它，并不一定是 bug。因此不会冒然修改这里的代码。每个人的标准是不一样的，您也可以 fork 一份按照下面去改。

> https://github.com/saintwinkle/hexo-theme-scribble/blob/master/source/css/style.css#L154
> 如果已经删掉了上面这行，请加回来；
> https://github.com/saintwinkle/hexo-theme-scribble/blob/master/source/css/style.css#L152
> 然后在这一行，把前面的 `a.main,` 去掉。

如果确实有影响体验和操作的 bug 存在，欢迎随时提出，谢谢。
