### ISSUE TITLE
主题根目录下_config.yml的about/ 404 问题 Email 404问题

### ISSUE THREAD

**Issue by smartbeng** [saintwinkle/hexo-theme-scribble#3]
关于_config.yml 的about ，我直接是在 about/ 后放入了我的新页面index.md，这个index.md 我是放在source目录下的 ，访问不到。Email 我是将原文件中的的邮箱换成了我的 mailto:stormzha@163.com，也出现了404，希望您在主页面添加修改此处的方法，也希望您帮我解答我的疑惑，谢谢。

**Comment by saintwinkle** [comment]
1. 关于 about 页面：请用 `hexo new page about` 创建新的 about 页面，命令行会显示 `index.md` 的正确路径，你的路径不对；
2. 关于 Email 问题：这是可选项，如果电脑里没有关联默认邮件客户端的话，估计是打不开的，可以在 `_config.yml` 文件中去掉这一行。`menu` 菜单下的其他也都是可选的，可根据自己的需求配置。

这其实不属于这个主题的问题，文档从头看下来会比较清楚 https://hexo.io/docs/

**Comment by smartbeng** [comment]
谢谢你！帮我解答的如此详细，我可以请教下关于主题代码高亮等一系列的设置，也是在以上这个文档里面看吗？

**Comment by saintwinkle** [comment]
这个主题是有代码高亮的，hexo 初始化的时候自带一篇 `Hello World` 示例文章，可以看到效果。如果已经删掉的话，可以看这里，大概就是这样的：http://chloerei.com/scribble/2013/10/11/placeholder-post/

**Comment by smartbeng** [comment]
![0k50wmv_2 lc0l2mt uhx3](https://cloud.githubusercontent.com/assets/22091836/24405122/4ac29010-13f6-11e7-8959-5d0cd7583e87.png)
![osh 3q tq0ntxlf 4443 8](https://cloud.githubusercontent.com/assets/22091836/24405140/5cf3bd90-13f6-11e7-8b7a-15be644c8cae.png)

谢谢您，但是您看一下，我也跟他一样用的是ruby，为什么我的出来是这个效果，非常希望您能不厌其烦解决我的困扰。

**Comment by smartbeng** [comment]
已经验证过了，我先clone了这个仓库，然后把他写的文件直接copy到了我的目录，结果出来就是上面这样的，这是不是一个bug呢！还是有别的地方我不知道。

**Comment by saintwinkle** [comment]
因为所用的样式不一样：[原版](https://github.com/chloerei/scribble/blob/master/stylesheets/syntax.css) | [本主题](https://github.com/saintwinkle/hexo-theme-scribble/blob/master/source/css/highlight.css)

原版样式中可以看到，`.c .err .cm .cp` 等 class 分别代表某种语言缩写，但是绝大多数我不知道是哪个；而本主题的样式则是类似 `.xml .ruby .python` 这样的全称，我没办法对应上的。

这就要考虑到 Jekyll 和 Hexo 两个博客系统的不同之处了，生成的 css class 不一样。

如果你想要改变代码高亮的话，只能自己改了，如果懂一点 css 的话：[配色方案](https://highlightjs.org/static/demo/) | [对应样式](https://github.com/isagalaev/highlight.js/tree/master/src/styles)

最后，代码行数是可以开关的，在根目录的 _config.yml 中编辑。

**Comment by stormzha** [comment]
非常感谢您这么耐心的回答，祝你工作顺利！

**Comment by smartbeng** [comment]
非常感谢你耐心解答，如此细心周到，祝您工作顺利！

**Comment by saintwinkle** [comment]
没事，同祝顺利。
