### ISSUE TITLE
为什么我的字体比较小？

### ISSUE THREAD

**Issue by blackshh** [saintwinkle/hexo-theme-scribble#4]

**Comment by saintwinkle** [comment]
因为这个主题的字体本来就很小。

**Comment by blackshh** [comment]
好的，有人copy了你的代码放在他的库里了，我觉得应该和你说一下。
这是地址：https://github.com/smartbeng/hexo-scribble @saintwinkle

**Comment by saintwinkle** [comment]
多谢提醒啊！看了下还真是 copy 我的，README 里面还有我的 id 没去掉哈哈哈，star 数居然还比我多 QAQ。以前把主题迁移到 hexo 也是练练手，忘了加 LICENSE，根据原主题的协议应该也用 MIT。

发现你去提了个 issue，那就看他愿不愿意加上 fork 自我这个 repo 的说明了。我也过去留个言做个说明好了。
